development:
  adapter: postgresql
  encoding: unicode
  database: textymous_development
  pool: 5
  username: josh
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: textymous_test
  pool: 5
  username: josh
  password: password1
