development:
  adapter: postgresql
  database: textymous_development
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  database: textymous_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: textymous_production
  pool: 5
  timeout: 5000
