# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af1a87ed6d24cb1b729e3b5c5ee4cde5d21292bc02573fd09cd3d29aebe7a261a2ed9d4a42c25f61d46c59c80429bd5d9146701d5c185352cd817b43c925d7ce

test:
  secret_key_base: 6792d23ce1e76c787f51d9f5acda6e4431dcd77900b526d4cf58e122112c2489b2c55bc5c179d67fc56484a25d8f364ae6c3fa63dcaa1f3b98b4a7e618094ae0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
